fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

soundcloud_login:
    pattern: /login/check-soundcloud

openriff:
    resource: "@App/Controller"
    type:     annotation

#openriff:
#    resource: "@App/Resources/config/routing.yml"
#    type:     "rad_convention"
